development:
  adapter: mysql2
  database: feed_development
  host: localhost
  port: 3306
  username: root
  password:

test:
  adapter: mysql2
  database: feed_test
  host: localhost
  port: 3306
  username: root
  password:
